/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import data.controladores.HallazgosControlador;
import data.controladores.ProyectoControlador;
import data.controladores.TareasControlador;
import static data.controladores.TareasControlador.listaTareas;
import data.controladores.UsuarioControlador;
import static data.controladores.UsuarioControlador.listaUsuarios;
import data.modelos.Estado;
import data.modelos.Proyecto;
import data.modelos.Tarea;
import data.modelos.Usuario;
import data.repositorios.TareasRepositorio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio
 */
public class MainWindow extends javax.swing.JFrame {
    public static String IDTareaSeleccionada;
    public static String IDEncargadoSeleccionado;
    public static String IDAsociadoSeleccionado;
    public static String IDUsuarioLogeado;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        ocultarTodo();
        setLocationRelativeTo(null);
    }
    public void ocultarTodo (){
        btnSeleccionarEncargado.setVisible(false);
        lblHallazgo.setVisible(false);
        txtHallazgo.setVisible(false);
        btnGuardarComentario.setVisible(false);
        btnGuardarEstado.setVisible(false);
        cbxEstados.setVisible(false);
        lblNombreProyecto.setVisible(false);
        txtNombreProyecto.setVisible(false);
        
        lblEncargado.setVisible(false);
        txtEncargado.setVisible(false);
        
        lblDescripcionProyecto.setVisible(false);
        txtDescripcionProyecto.setVisible(false);
        
        lblEstado.setVisible(false);
        txtEstado.setVisible(false); 
        
        lblNombreTarea.setVisible(false);
        txtNombreTarea.setVisible(false);
        
        lblDescripcionTarea.setVisible(false);
        txtDescripcionTarea.setVisible(false);
        
        lblListaDeTareas.setVisible(false);
        lblListaDeAsociados.setVisible(false);
        
        btnAgregarTarea.setVisible(false);
        btnAgregarComentario.setVisible(false);
        btnCambiarEstado.setVisible(false);
        btnGuardarProyecto.setVisible(false);
        btnGuardarTarea.setVisible(false);
        btnAgregarAsociados.setVisible(false);
        btnEliminarTarea.setVisible(false);
        btnEliminarAsociados.setVisible(false);
        btnAgregarEncargadoTarea.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        cbxProyectos = new javax.swing.JComboBox<>();
        lblNombreProyecto = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        lblEncargado = new javax.swing.JLabel();
        txtEncargado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        lblListaDeTareas = new javax.swing.JLabel();
        btnAgregarTarea = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblSeleccioneProyecto = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAgregarProyecto = new javax.swing.JButton();
        lblDescripcionProyecto = new javax.swing.JLabel();
        txtDescripcionProyecto = new javax.swing.JTextField();
        btnAgregarComentario = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();
        btnGuardarProyecto = new javax.swing.JButton();
        btnGuardarTarea = new javax.swing.JButton();
        txtNombreTarea = new javax.swing.JTextField();
        lblNombreTarea = new javax.swing.JLabel();
        btnAgregarAsociados = new javax.swing.JButton();
        btnEliminarAsociados = new javax.swing.JButton();
        lblDescripcionTarea = new javax.swing.JLabel();
        txtDescripcionTarea = new javax.swing.JTextField();
        lblListaDeAsociados = new javax.swing.JLabel();
        btnEliminarTarea = new javax.swing.JButton();
        btnAgregarEncargadoTarea = new javax.swing.JButton();
        cbxEstados = new javax.swing.JComboBox<>();
        btnGuardarEstado = new javax.swing.JButton();
        btnGuardarComentario = new javax.swing.JButton();
        lblHallazgo = new javax.swing.JLabel();
        txtHallazgo = new javax.swing.JTextField();
        btnSeleccionarEncargado = new javax.swing.JButton();
        btnSeleccionarAsociado = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("txtNombreTarea"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxProyectos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Proyecto 1", "Proyecto2" }));
        cbxProyectos.setName("cbxProyectos"); // NOI18N
        getContentPane().add(cbxProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 180, 40));

        lblNombreProyecto.setText("Nombre del proyecto:");
        lblNombreProyecto.setName("lblNombreProyecto"); // NOI18N
        getContentPane().add(lblNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtNombreProyecto.setName("txtNombreProyecto"); // NOI18N
        getContentPane().add(txtNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 62, 270, 30));

        lblEncargado.setText("Encargado:");
        lblEncargado.setName("lblEncargado"); // NOI18N
        getContentPane().add(lblEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        txtEncargado.setName("txtEncargado"); // NOI18N
        getContentPane().add(txtEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 210, 30));

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrincipal.setName("tblPrincipal"); // NOI18N
        tblPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrincipal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 1120, 360));

        lblListaDeTareas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblListaDeTareas.setText("Tareas");
        lblListaDeTareas.setName("lblListaDeTareas"); // NOI18N
        getContentPane().add(lblListaDeTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        btnAgregarTarea.setText("Agregar Tarea");
        btnAgregarTarea.setName("btnAgregarTarea"); // NOI18N
        btnAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Control de Proyectos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblSeleccioneProyecto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSeleccioneProyecto.setText("Seleccione el Proyecto");
        lblSeleccioneProyecto.setName("lblSeleccioneProyecto"); // NOI18N
        getContentPane().add(lblSeleccioneProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        lblEstado.setText("Estado:");
        lblEstado.setName("lblEstado"); // NOI18N
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        txtEstado.setName("txtEstado"); // NOI18N
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 130, 30));

        btnAgregarProyecto.setText("Agregar Proyecto");
        btnAgregarProyecto.setName("btnAgregarProyecto"); // NOI18N
        btnAgregarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 40));

        lblDescripcionProyecto.setText("Descripción del Proyecto:");
        lblDescripcionProyecto.setName("lblDescripcionProyecto"); // NOI18N
        getContentPane().add(lblDescripcionProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtDescripcionProyecto.setName("txtDescripcionProyecto"); // NOI18N
        getContentPane().add(txtDescripcionProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 930, 30));

        btnAgregarComentario.setText("Agregar Hallazgo");
        btnAgregarComentario.setName("btnAgregarComentario"); // NOI18N
        btnAgregarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComentarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 140, 30));

        btnCambiarEstado.setText("Cambiar Estado");
        btnCambiarEstado.setName("btnCambiarEstado"); // NOI18N
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 120, 40));

        btnGuardarProyecto.setText("Guardar ");
        btnGuardarProyecto.setName("btnGuardarProyecto"); // NOI18N
        btnGuardarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 40));

        btnGuardarTarea.setText("Guardar Tarea");
        btnGuardarTarea.setName("btnGuardarTarea"); // NOI18N
        btnGuardarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 40));
        getContentPane().add(txtNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 300, -1));

        lblNombreTarea.setText("Nombre tarea:");
        lblNombreTarea.setName("lblNombreTarea"); // NOI18N
        getContentPane().add(lblNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        btnAgregarAsociados.setText("Agregar Asociados");
        btnAgregarAsociados.setName("btnAgregarAsociados"); // NOI18N
        btnAgregarAsociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAsociadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarAsociados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, 30));

        btnEliminarAsociados.setText("Eliminar Asociados");
        btnEliminarAsociados.setName("btnEliminarAsociados"); // NOI18N
        getContentPane().add(btnEliminarAsociados, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 130, 30));

        lblDescripcionTarea.setText("Descripcion Tarea:");
        lblDescripcionTarea.setName("lblDescripcionTarea"); // NOI18N
        getContentPane().add(lblDescripcionTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        txtDescripcionTarea.setName("txtDescripcionTarea"); // NOI18N
        txtDescripcionTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionTareaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcionTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 300, -1));

        lblListaDeAsociados.setText("Lista de asociados");
        lblListaDeAsociados.setName("lblListaDeAsociados"); // NOI18N
        getContentPane().add(lblListaDeAsociados, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        btnEliminarTarea.setText("Eliminar Tarea");
        btnEliminarTarea.setName("btnEliminarTarea"); // NOI18N
        btnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 30));

        btnAgregarEncargadoTarea.setText("Agregar Encargado");
        btnAgregarEncargadoTarea.setName("btnAgregarEncargadoTarea"); // NOI18N
        btnAgregarEncargadoTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEncargadoTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarEncargadoTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 140, 40));

        cbxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Pendiente", "En desarrollo", "Suspendida", "Cancelada", "Terminada" }));
        cbxEstados.setName("cbxEstados"); // NOI18N
        cbxEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadosActionPerformed(evt);
            }
        });
        getContentPane().add(cbxEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 120, 40));

        btnGuardarEstado.setText("Guardar Estado");
        btnGuardarEstado.setName("btnGuardarEstado"); // NOI18N
        btnGuardarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 120, 40));

        btnGuardarComentario.setText("Guardar Hallazgo");
        btnGuardarComentario.setName("btnGuardarComentario"); // NOI18N
        btnGuardarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComentarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, 30));

        lblHallazgo.setText("Hallazgo:");
        lblHallazgo.setName("lblHallazgo"); // NOI18N
        getContentPane().add(lblHallazgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        txtHallazgo.setName("txtHallazgo"); // NOI18N
        txtHallazgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHallazgoActionPerformed(evt);
            }
        });
        getContentPane().add(txtHallazgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 300, -1));

        btnSeleccionarEncargado.setText("Seleccionar Encargado");
        btnSeleccionarEncargado.setName("btnSeleccionarEncargado"); // NOI18N
        btnSeleccionarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarEncargadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 150, 40));

        btnSeleccionarAsociado.setText("Seleccionar Asociado");
        btnSeleccionarAsociado.setName("btnSeleccionarAsociado"); // NOI18N
        btnSeleccionarAsociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarAsociadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarAsociado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void botonGuardarProyecto()
    {
        lblSeleccioneProyecto.setVisible(false);
        cbxProyectos.setVisible(false);
        lblNombreProyecto.setVisible(true);
        txtNombreProyecto.setEnabled(false);
        
        lblEncargado.setVisible(true);
        txtEncargado.setEnabled(false);
        
        lblDescripcionProyecto.setVisible(true);
        txtDescripcionProyecto.setEnabled(false);
        
        lblEstado.setVisible(true);
        txtEstado.setEnabled(false); 
        
        lblNombreTarea.setVisible(false);
        txtNombreTarea.setEnabled(false);
        
        lblDescripcionTarea.setVisible(false);
        txtDescripcionTarea.setEnabled(false);
        
        lblListaDeTareas.setVisible(false);
        lblListaDeAsociados.setVisible(false);
        
        btnAgregarTarea.setVisible(true);
        btnAgregarComentario.setVisible(true);
        btnCambiarEstado.setVisible(true);
        btnGuardarProyecto.setVisible(false);
        btnGuardarTarea.setVisible(false);
        btnAgregarAsociados.setVisible(true);
        btnEliminarTarea.setVisible(false);
        btnEliminarAsociados.setVisible(false);
        btnAgregarEncargadoTarea.setVisible(true);
        btnEliminarAsociados.setVisible(true);
        
    }
    private void btnGuardarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProyectoActionPerformed
        botonGuardarProyecto();
    }//GEN-LAST:event_btnGuardarProyectoActionPerformed
    public void botonAgregarProyecto()
    {
        lblNombreProyecto.setVisible(true);
        txtNombreProyecto.setVisible(true);
        txtNombreProyecto.setEnabled(true);
        txtNombreProyecto.setText("");
        
        lblEncargado.setVisible(true);
        txtEncargado.setVisible(true);
        txtEncargado.setEnabled(true);
        txtEncargado.setText("");
        
        lblDescripcionProyecto.setVisible(true);
        txtDescripcionProyecto.setVisible(true);
        txtDescripcionProyecto.setEnabled(true);
        txtDescripcionProyecto.setText("");
        
        btnAgregarProyecto.setVisible(false);
        btnGuardarProyecto.setVisible(true);
        
        lblEstado.setVisible(false);
        txtEstado.setVisible(false); 
        
        lblNombreTarea.setVisible(false);
        txtNombreTarea.setVisible(false);
        
        lblDescripcionTarea.setVisible(false);
        txtDescripcionTarea.setVisible(false);
        
        lblListaDeTareas.setVisible(false);
        lblListaDeAsociados.setVisible(false);
        
        btnAgregarTarea.setVisible(false);
        btnAgregarComentario.setVisible(false);
        btnCambiarEstado.setVisible(false);
        btnGuardarTarea.setVisible(false);
        btnAgregarAsociados.setVisible(false);
        btnEliminarTarea.setVisible(false);
        btnEliminarAsociados.setVisible(false);
        lblSeleccioneProyecto.setVisible(false);
        cbxProyectos.setVisible(false);
        
    }
    public String proyectoId;
    private void btnAgregarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProyectoActionPerformed
        Proyecto proyecto = new Proyecto();
        proyecto.setNombre(txtNombreProyecto.getText());
        proyecto.setDescripción(txtDescripcionProyecto.getText());
        ProyectoControlador.agregarProyecto(proyecto);
        botonAgregarProyecto();
    }//GEN-LAST:event_btnAgregarProyectoActionPerformed
    public void botonAgregarTarea()
    {
        lblNombreTarea.setVisible(true);
        txtNombreTarea.setEnabled(true);
        txtNombreTarea.setVisible(true);
        btnAgregarTarea.setVisible(false);
        btnGuardarTarea.setVisible(true);
        lblDescripcionTarea.setVisible(true);
        txtDescripcionTarea.setVisible(true);
        txtDescripcionTarea.setEnabled(true);
        txtDescripcionTarea.setText("");
        
        
    }
    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
       
        botonAgregarTarea();
    }//GEN-LAST:event_btnAgregarTareaActionPerformed
    public String tareaId;
    public void botonGuardarTarea()
    {
        //metodo de guardar
        lblNombreTarea.setVisible(false);
        txtNombreTarea.setText("");
        btnAgregarTarea.setVisible(true);
        btnGuardarTarea.setVisible(false);
        txtNombreTarea.setVisible(false);
        btnEliminarTarea.setVisible(true);
        lblDescripcionTarea.setVisible(false);
        txtDescripcionTarea.setVisible(false);
        txtDescripcionTarea.setText("");
        
    }
    private void actualizarTablaParaSeleccionarElEncargado(ArrayList<Usuario> listaUsuarios)
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
        Object[] fila = new Object [5];
        
        for (Usuario usuario : listaUsuarios())
        {
            fila[0]= usuario.getId();
            fila[1]= usuario.getNombre();
            fila[2]= usuario.getPrimerApellido();
            fila[3]= usuario.getTeléfono(); 
            fila[4]= usuario.getCorreoElectrónico();
            modelo.addRow(fila);
        }
        tblPrincipal.setModel(modelo);
    }
    private void actualizarTablaDeTareas(ArrayList<Tarea> listaTareas)
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Tarea");
        modelo.addColumn("Descripción");
        modelo.addColumn("Encargado");
        modelo.addColumn("Hallazgos");
        modelo.addColumn("Estado");
        modelo.addColumn("Asociados");
        Object[] fila = new Object [7];
        
        for (Tarea tarea : listaTareas)
        {
            Usuario usuario = UsuarioControlador.getUsuario(tarea.getResponsableId());
            String NombreCompleto = "";
            if (usuario!=null)
            {
               NombreCompleto = usuario.getNombre() + " " + usuario.getPrimerApellido(); 
            }
            String EstadoTarea="";
            if (tarea.getEstado()!=null)
            {
                EstadoTarea = tarea.getEstado().toString().replace("_", " ").toLowerCase();
            }
            int asociados=0;
            if (tarea.getAsociados()!=null)
            {
                asociados=tarea.getAsociados().size();
            }
            fila[0]= tarea.getId();
            fila[1]= tarea.getNombre();
            fila[2]= tarea.getDescripción();
            fila[3]= NombreCompleto;
            fila[4]= TareasControlador.obtenerHallazgosDeTarea(tarea.getId()).size();
            fila[5]= EstadoTarea;
            fila[6]= asociados;
            modelo.addRow(fila);
        }
        tblPrincipal.setModel(modelo);
    }
    private void btnGuardarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTareaActionPerformed
        Tarea tarea = new Tarea();
        //ArrayList<Tarea> listadetareas = TareasControlador.listaTareas();
        tarea.setNombre(txtNombreTarea.getText());
        tarea.setProyectoId(proyectoId);
        tarea.setDescripción(txtDescripcionTarea.getText());
        TareasControlador.agregarTarea(tarea);
        botonGuardarTarea();
        ArrayList<Tarea> listaTareas= TareasControlador.listaTareas(); 
        actualizarTablaDeTareas(listaTareas);
        
        /*  public static ArrayList<Tarea> listaTareas(){
        return tareasRepositorio.getTareas();*/
    }//GEN-LAST:event_btnGuardarTareaActionPerformed

    private void cbxEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadosActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        cbxEstados.setVisible(true);
        btnCambiarEstado.setVisible(false);
        btnGuardarEstado.setVisible(true);
        int selectedRow = tblPrincipal.getSelectedRow();
        IDTareaSeleccionada = tblPrincipal.getValueAt(selectedRow, 0).toString();
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnGuardarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstadoActionPerformed
        cbxEstados.setVisible(false);
        btnCambiarEstado.setVisible(true);
        btnGuardarEstado.setVisible(false);       
       Tarea tarea = TareasControlador.obtenerTarea(IDTareaSeleccionada);
       if (cbxEstados.getSelectedItem()=="Pendiente")
       {
           tarea.setEstado(Estado.PENDIENTE);
       }else if(cbxEstados.getSelectedItem()=="En desarrollo")
       {
           tarea.setEstado(Estado.EN_DESARROLLO);
       }else if(cbxEstados.getSelectedItem()=="Suspendida")
       {
           tarea.setEstado(Estado.SUSPENDIDA);
       }else if(cbxEstados.getSelectedItem()=="Cancelada")
       {
           tarea.setEstado(Estado.CANCELADA);
       }else if(cbxEstados.getSelectedItem()=="Terminada")
       {
           tarea.setEstado(Estado.TERMINADA);
       }
       ArrayList<Tarea> listaTareas= TareasControlador.listaTareas(); 
        actualizarTablaDeTareas(listaTareas);
    }//GEN-LAST:event_btnGuardarEstadoActionPerformed

    private void btnAgregarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComentarioActionPerformed
        btnAgregarComentario.setVisible(false);
        lblHallazgo.setVisible(true);
        btnGuardarComentario.setVisible(true);
        txtHallazgo.setVisible(true);
    }//GEN-LAST:event_btnAgregarComentarioActionPerformed

    private void btnGuardarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComentarioActionPerformed
        // metodo de guardar comentario en el array
        btnGuardarComentario.setVisible(false);
        btnAgregarComentario.setVisible(true);
        txtHallazgo.setText("");
        lblHallazgo.setVisible(false);
        txtHallazgo.setVisible(false);
        
    }//GEN-LAST:event_btnGuardarComentarioActionPerformed
    
    private void btnAgregarEncargadoTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEncargadoTareaActionPerformed
        btnSeleccionarEncargado.setVisible(true);
        btnAgregarEncargadoTarea.setVisible(false);
        int selectedRow = tblPrincipal.getSelectedRow();
        IDTareaSeleccionada = tblPrincipal.getValueAt(selectedRow, 0).toString();
        ArrayList<Usuario> listaUsuarios= UsuarioControlador.listaUsuarios();
        actualizarTablaParaSeleccionarElEncargado(listaUsuarios);
        
        /*ArrayList<Tarea> listaTareas= TareasControlador.listaTareas(); 
        actualizarTablaDeTareas(listaTareas); 
        */
    }//GEN-LAST:event_btnAgregarEncargadoTareaActionPerformed

    private void txtDescripcionTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionTareaActionPerformed

    private void txtHallazgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHallazgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHallazgoActionPerformed

    private void tblPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrincipalMouseClicked
        
    }//GEN-LAST:event_tblPrincipalMouseClicked

    private void btnSeleccionarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarEncargadoActionPerformed
       btnAgregarEncargadoTarea.setVisible(true);
       btnSeleccionarEncargado.setVisible(false);
        int selectedRow = tblPrincipal.getSelectedRow();
       IDEncargadoSeleccionado = tblPrincipal.getValueAt(selectedRow, 0).toString();
       Tarea tarea = TareasControlador.obtenerTarea(IDTareaSeleccionada);
       tarea.setResponsableId(IDEncargadoSeleccionado);
       ArrayList<Tarea> listaTareas= TareasControlador.listaTareas(); 
        actualizarTablaDeTareas(listaTareas);
    }//GEN-LAST:event_btnSeleccionarEncargadoActionPerformed

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed
        int selectedRow = tblPrincipal.getSelectedRow();
        IDTareaSeleccionada = tblPrincipal.getValueAt(selectedRow, 0).toString();
        TareasControlador.eliminarTarea(IDTareaSeleccionada);
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnAgregarAsociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAsociadosActionPerformed
        btnAgregarAsociados.setVisible(false);
        btnSeleccionarAsociado.setVisible(true);
        int selectedRow = tblPrincipal.getSelectedRow();
        IDTareaSeleccionada = tblPrincipal.getValueAt(selectedRow, 0).toString();
        ArrayList<Usuario> listaUsuarios= UsuarioControlador.listaUsuarios();
        actualizarTablaParaSeleccionarElEncargado(listaUsuarios);
    }//GEN-LAST:event_btnAgregarAsociadosActionPerformed

    private void btnSeleccionarAsociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarAsociadoActionPerformed
        btnAgregarAsociados.setVisible(true);
        btnSeleccionarAsociado.setVisible(false);
        int selectedRow = tblPrincipal.getSelectedRow();
        IDAsociadoSeleccionado = tblPrincipal.getValueAt(selectedRow, 0).toString();
        Tarea tarea = TareasControlador.obtenerTarea(IDTareaSeleccionada);
        tarea.agregarAsociado(UsuarioControlador.getUsuario(IDAsociadoSeleccionado));
        ArrayList<Tarea> listaTareas= TareasControlador.listaTareas(); 
        actualizarTablaDeTareas(listaTareas);
    }//GEN-LAST:event_btnSeleccionarAsociadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAsociados;
    private javax.swing.JButton btnAgregarComentario;
    private javax.swing.JButton btnAgregarEncargadoTarea;
    private javax.swing.JButton btnAgregarProyecto;
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnEliminarAsociados;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JButton btnGuardarComentario;
    private javax.swing.JButton btnGuardarEstado;
    private javax.swing.JButton btnGuardarProyecto;
    private javax.swing.JButton btnGuardarTarea;
    private javax.swing.JButton btnSeleccionarAsociado;
    private javax.swing.JButton btnSeleccionarEncargado;
    private javax.swing.JComboBox<String> cbxEstados;
    private javax.swing.JComboBox<String> cbxProyectos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionProyecto;
    private javax.swing.JLabel lblDescripcionTarea;
    private javax.swing.JLabel lblEncargado;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHallazgo;
    private javax.swing.JLabel lblListaDeAsociados;
    private javax.swing.JLabel lblListaDeTareas;
    private javax.swing.JLabel lblNombreProyecto;
    private javax.swing.JLabel lblNombreTarea;
    private javax.swing.JLabel lblSeleccioneProyecto;
    public javax.swing.JTable tblPrincipal;
    private javax.swing.JTextField txtDescripcionProyecto;
    private javax.swing.JTextField txtDescripcionTarea;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtHallazgo;
    private javax.swing.JTextField txtNombreProyecto;
    private javax.swing.JTextField txtNombreTarea;
    // End of variables declaration//GEN-END:variables
}
